###
Saves our redux state to local storage
###
(make saveState [state]
  (attempt :save-state
    (do
      (make serialized (JSON.stringify state))
      (localStorage.setItem 'maple' serialized))))

###
Retrieves a previous state from local storage
###
(make retrieveState []
  (attempt :get-state
    (do
      (make serialized (localStorage.getItem 'maple'))
      (JSON.parse serialized))))

###
Creates a unique ID
###
(make uniqueId []
  (make time (-> (instance Date) (@getTime)))
  (make rand (Math.round (* (Math.random) 50000)))
  (+ time '-' rand))

# Export our state functions
(export [saveState retrieveState uniqueId])
